
language: minimal
sudo: false

script: bin/test

services:
  - postgresql

jobs:
  include:
  - name: "Postgres 9.4"
    addons:
      postgresql: 9.4
      apt:
        packages:
          - postgresql-9.4
          - postgresql-client-9.4

  - name: "Postgres 9.5"
    addons:
      postgresql: 9.5
      apt:
        packages:
          - postgresql-9.5
          - postgresql-client-9.5

  - name: "Postgres 9.6"
    addons:
      postgresql: 9.6
      apt:
        packages:
          - postgresql-9.6
          - postgresql-client-9.6

  - name: "Postgres 10"
    addons:
      postgresql: 10
      apt:
        packages:
          - postgresql-10
          - postgresql-client-10

  - name: "Postgres 11"
    addons:
      postgresql: 11
      apt:
        packages:
          - postgresql-11
          - postgresql-client-11

  - name: "Postgres 12"
    addons:
      postgresql: 12
      apt:
        packages:
          - postgresql-12
          - postgresql-client-12